### REQUIRED SETTINGS ###

# Set a plain language title for the site.
title: Amtrak

# Write a short description for the site. This is used for "meta description."
description: With over 500 destinations, Amtrak takes you where you want to go.

# Enable for live hosting on GitHub Pages
# This should match the name of your GitHub repository, along with a leading forward slash (/).
baseurl: /trip-planner

### RECOMMENDED SETTINGS ###

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Avoid GitHub API authentication when building locally.
# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
github: [metadata]

# Remove generation of additional style.css
theme: null